### ISSUE TITLE
[Discuss] 有靠谱的时间记录工具否?

### ISSUE THREAD

**Issue by xpgeng** [DebugUself/prototype#3]
~ @DebugUself/du4all  
## 背景

- S01E01 已经开车, 可是对于以前并未过多研究过记录时间的一众怼友们, 简直是炸毛...
- 怎么记?
- 拿什么记?

## 问题

那么, 你有没有靠谱的工具或者解决方式帮助大家**高效**的记录好每日的时间开销? 

## 分享格式

- 工具名称?
- 适用平台?
- 可用功能?
- 优点?
- 缺点?

> PS: 工具确实重要, 但不要因为工具, 而忽视我们的目的-- 记录.   
> 所以, 如果你还没找到一个靠谱的工具, 索性先拿着一个用起来.

**Comment by NBR-hugh** [comment]
- 工具名称? 
[时间块 - 超快记录时间, 无需按开始停止](https://itunes.apple.com/cn/app/%E6%97%B6%E9%97%B4%E5%9D%97-%E8%B6%85%E5%BF%AB%E8%AE%B0%E5%BD%95%E6%97%B6%E9%97%B4-%E6%97%A0%E9%9C%80%E6%8C%89%E5%BC%80%E5%A7%8B%E5%81%9C%E6%AD%A2/id1086617993?mt=8)

- 适用平台?

>兼容性： 需要 iOS 8.0 或更高版本。与 iPhone、iPad 和 iPod touch 兼容。

- 可用功能?
  + 快速记录时间
  + 生成记录快照
- 优点?
  + 记得快…… 记录阻力小
  + 事件类别自由组合
  + 记录单位自己调整 
  + 可以看日／周／月趋势和统计，虽然有点丑
  + 以图片形式呈现每日报告
- 缺点?
  + 付费，12大洋
  + 丑萌

**Comment by ZoomQuiet** [comment]
CANCEL for overflow ;-( 放弃/转义/过期....

-->

[[Discuss] 有靠谱的时间记录工具否? · Issue #3 · DebugUself/du4proto](https://github.com/DebugUself/du4proto/issues/3)
